Encoder:  
- Word Vocab 
- Normal Encode


-> Hidden_state -> Decoder 

Decoder:
- Phoneme Vocab 
- 4 embedding layer + Concat 4 layer - Decoder layer
- Decoder output: (B, S, hidden_size)
- 4 Feed-Forward Layers
- ViPhoneme decode 



`viword_vocab` methods: 
- `make_vocab`
- `encode_caption`
- `decode_caption`
- `decode_batch_caption`


Shapes: 
- `input:` (B, S, 3)
- `bos input:` (bos_idx, pad_idx, pad_idx)
- `eos input:` (eos_idx, pad_idx, pad_idx)


`TextSumDatasetPhoneme` methods: 
- `make_vocab`
- `encode_caption`
- `decode_caption`
- `decode_batch_caption`

Shapes: 
- `input_ids`: (bos_idx, pad_idx, pad_idx) + (onset, middle, lower) + (eos_idx, pad_idx, pad_idx)
- `label`: (bos_idx, pad_idx, pad_idx) + (onset, middle, lower) + (eos_idx, pad_idx, pad_idx)
- `shifted_right_label`: (onset, middle, lower) + (eos_idx, pad_idx, pad_idx)

In [10]:
import torch 

In [11]:
data = [20, 15, 40]

In [12]:
data = torch.Tensor(data)

In [16]:
import torch

data = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
]

data = torch.Tensor(data)

print(data)
print(data.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])


In [24]:
data.size()[-1]

3

In [26]:
from torch import nn

class FeedForward(nn.Module):
    def __init__(self, input: torch.Tensor):
        super(FeedForward, self).__init__()
        self.hidden_size = input.size()[-1]
        self.norm = nn.LayerNorm(self.hidden_size)
        self.linear_projection_1 = nn.Linear(self.hidden_size, \
                                            self.hidden_size * 2)
        self.ReLu = nn.ReLU()
        self.linear_projection_2 = nn.Linear(self.hidden_size*2,\
                                            self.hidden_size)

    def forward(self, x):
        x = self.norm(x)
        x_rest = x
        x = self.ReLu(self.linear_projection_1(x))
        x = self.linear_projection_2(x)
        x += x_rest 
        return x
    
ff = FeedForward(data)
x = ff.forward(data)

In [30]:
x

tensor([[[-1.0705,  0.4015,  1.2111],
         [-1.0705,  0.4015,  1.2111]],

        [[-1.0705,  0.4015,  1.2111],
         [-1.0705,  0.4015,  1.2111]]], grad_fn=<AsStridedBackward0>)

In [31]:
data

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [32]:
import torch

a = torch.tensor([[1,2]])
b = torch.tensor([[3,4]])

print(torch.cat([a,b], dim=0))
print(torch.concat([a,b], dim=0))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [33]:
import torch

batch_size = 4
hidden_size = 128

x = torch.randn(batch_size, 1, hidden_size * 3)

print(x.shape)

torch.Size([4, 1, 384])


In [2]:
total = [3,4,5,6]
test = sum(total)
test

18

In [4]:
import torch
x = torch.tensor([[5]])
print(x.item())

5


In [5]:
data = [[4, 5, 6], [5, 6, 7]]

In [7]:
len(data[0])

3